version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    working_directory: ~/mosaic
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get upgrade -y
      - run: sudo apt-get install -y libgl1-mesa-dev
      - python/install-packages:
          pkg-manager: pip

  deploy: # 任意の名前をお選びください。
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # build_and_test ジョブが完了している場合のみデプロイします。
          filters:
            branches:
              only: main # main にある場合のみデプロイします。
