version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get upgrade -y
      - run: sudo apt-get install -y libgl1-mesa-dev
      - python/install-packages:
          pkg-manager: pip
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy: # 任意の名前をお選びください。
    docker:
      - image: cimg/python:3.10.1
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
      - run:
          name: runserver
          command: python3 ~/code/server.py

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # build_and_test ジョブが完了している場合のみデプロイします。
          filters:
            branches:
              only: main # main にある場合のみデプロイします。
